pipeline {
    agent any

    environment {
       GIT_REPO = 'https://github.com/iGovTT/VerifyTT.git'
       MANIFEST_BRANCH = 'master'
    }

    stages {
       
        stage('Build') { 
            steps {
                dir('service/welearn-tt-esignet-integration-impl') {
                        sh '''#!/bin/bash
                        export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
                        export PATH="$JAVA_HOME/bin:$PATH"
                        mvn -B -DskipTests clean package
                        ''' 
                }
                
            }
        }
        stage('Push Jar artificatory') { 
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'githubpat2', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                        sh """
                        rm -rf VerifyTT
                        # Clone manifest repo
                        git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/iGovTT/VerifyTT.git
                        cd VerifyTT
                        ls
                        git checkout ${env.BRANCH_NAME}
                        rm -rf ./service/artifactory/welearn-tt-esignet-integration-impl*
                        cp ../service/welearn-tt-esignet-integration-impl/target/welearn-tt-esignet-integration-impl-0.3.0.jar ./service/artifactory/
                        
                        git status
                        # Commit & Push changes if there are any
                        git add service/artifactory/welearn-tt-esignet-integration-impl-0.3.0.jar
                        git commit -m "Update certify plugin" || echo "No changes to commit"
                        git push origin ${env.BRANCH_NAME}
                        """
                    }
                }
            }
        }
    }
        
    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Failed!"
        }
    }
}
